modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0"
[[mods]]
modId="extrakeybinds"
version="${file.jarVersion}"
displayName="CyaConnors Extra Origins Keybinds"
logoFile="assets/extrakeybinds/icon.png"
authors="CyaConnor, RadonCoding"
description='''
Adds more keybinds to the Origins mod.
'''

[[dependencies.extrakeybinds]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrakeybinds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
